### ISSUE TITLE
Improvements to `catleg skeleton`'s output

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catleg#45]
Hi @rprimet ! Thanks very much for your work on `catleg skeleton`. We used it last week and here's a couple improvements I've noticed can be made:

* The number of `#` in front of the headings should be `nesting_level + 1`, the `+ 1` is because we have a first title for the code (`# Code des impôts`)
* Some headings are in bold (`* ... *`) in markdown, I don't think we should keep that
* The newlines in the text of the article are not preserved by `catleg skeleton` but they should, a newline on LégiFrance should be `\n\n` in the output of `catleg skeleton`.
* When the `NOTA` is empty, don't print `NOTA`
* The `NOTA:` should be with the following format: `<end of article>\n\nNOTA :\n\n<text of NOTA>`

**Comment by rprimet** [comment]
Thanks, closing this now that #46 is merged
