### ISSUE TITLE
Add options to ignore links and process escapements in `catleg diff`

### ISSUE THREAD

**Issue by rprimet** [CatalaLang/catleg#55]
After trying `catleg diff` on an extract of [the IR repo](https://gitlab.adullact.net/dgfip/ir-catala), I noticed a few possible improvements (i.e. diffs that could/should not be reported as such but may be spurious):

- markdown sometimes requires escapements: for instance for square brackets, so escaped brackets (  `\[2°\]` ) or stars (`\*`) should not be reported. I am not sure what is the best way of addressing this, converting the reference text to markdown or some other approach?
- links are sometimes inserted between articles, so links might be handled specially (we could ignore links, or check that they point to the right target...). For instance in `cgi_revenus.catala_fr`:

```
 [200 C](/affichCodeArticle.do?cidTexte=LEGITEXT000006069577&idArticle=LEGIARTI000037943290&dateTexte=&categorieLien=cid)
```
(by the way, this is not a complete/valid URL, @denismerigoux @AltGr is there some specific convention?)

**Comment by denismerigoux** [comment]
> markdown sometimes requires escapements: for instance for square brackets, so escaped brackets ( \[2°\] ) or stars (\*) should not be reported. I am not sure what is the best way of addressing this, converting the reference text to markdown or some other approach?

As I understand correctly in `catleg diff` you parse the Catala source code text as markdown right? If yes then does your markdown parsing library offer a feature to render markdown as text, and thus de-escaping the brackets, stars, etc. ?

> links are sometimes inserted between articles, so links might be handled specially (we could ignore links, or check that they point to the right target...). 

I would go with simply ignoring all link targets for `catleg diff`.

**Comment by rprimet** [comment]
> As I understand correctly in catleg diff you parse the Catala source code text as markdown right? If yes then does your markdown parsing library offer a feature to render markdown as text, and thus de-escaping the brackets, stars, etc. ?

Yep, should do that, makes more sense than going the other way round :)

**Comment by rprimet** [comment]
Actually, looking at links, maybe those ones  ` [200 C](/affichCodeArticle.do?cidTexte=LEGITEXT000006069577&idArticle=LEGIARTI000037943290&dateTexte=&categorieLien=cid)` are spurious and were inserted by the skeleton generator?

**Comment by denismerigoux** [comment]
Perhaps, in this case they should be removed (just keep the text of the link).

**Comment by rprimet** [comment]
Yep, I think so, I'll check what the skeleton generator does by default, but keeping the link text and stripping the link seems a good default behavior.

**Comment by rprimet** [comment]
I think we can close this when #58 is merged
