### ISSUE TITLE
remove `catleg query`

### ISSUE THREAD

**Issue by rprimet** [CatalaLang/catleg#67]
For now, I think `catleg query` is not yet very useful as a standalone CLI tool, we could revisit when there are multiple backends maybe? But I think we could remove that command for the time being, as `catleg lf article` is more useful

@denismerigoux @AltGr any thoughts?

Related: #22 #43

**Comment by denismerigoux** [comment]
Yes catleg query is not very useful, and yes an equivalent of catleg skeleton but with only one article ID would be useful!
