### ISSUE TITLE
List numbers wrong for skeleton output

### ISSUE THREAD

**Issue by denismerigoux** [CatalaLang/catleg#71]
When running `catleg skeleton LEGITEXT000006069577 LEGISCTA000006179571`, for "Article 13" the first 3 enumerated items are 1. instead of 1., 2. and 3.

**Comment by rprimet** [comment]
I can reproduce this, looking into it, thanks for the catch!

**Comment by denismerigoux** [comment]
So for some reason there's still a problem in the French income tax lint with these list numbers : https://gitlab.adullact.net/dgfip/ir-catala/-/jobs/191411

**Comment by rprimet** [comment]
@denismerigoux was the skeleton generated with the latest `catleg` version?

Trying `catleg article LEGIARTI000044983201` seems to yield the correct numbering?

**Comment by denismerigoux** [comment]
> Trying catleg article LEGIARTI000044983201 seems to yield the correct numbering?

Locally on my machine yes... Maybe it's a problem with fetching the latest `catleg` version here ? https://gitlab.inria.fr/verifisc/docker-catala/-/blob/master/Dockerfile?ref_type=heads#L20

**Comment by denismerigoux** [comment]
@AltGr are you sure the Catala CI image gets an updated `catleg` with https://gitlab.inria.fr/verifisc/docker-catala/-/blob/master/Dockerfile?ref_type=heads#L20 ?

**Comment by rprimet** [comment]
@denismerigoux yes but it's not a CI problem, more like which version was used to (hand-)generate the skeleton that was then committed during a pair-programming session?

**Comment by denismerigoux** [comment]
No, the version in the source code against which `catleg` lints is fine : https://gitlab.adullact.net/dgfip/ir-catala/-/blob/main/sources/cgi_revenus.catala_fr?ref_type=heads#L65-112 (the diff from the lint job is here https://gitlab.adullact.net/dgfip/ir-catala/-/jobs/193158#L25).

**Comment by rprimet** [comment]
OK, thanks, I can reproduce the issue now
